const express = require('express');
const path = require('path');
const multer = require('multer');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const QRCode = require('qrcode');
const { createClient } = require('@supabase/supabase-js');
const { v4: uuid } = require('uuid');

const app = express();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });
const supabase = createClient(process.env.SUPABASE_URL || '', process.env.SUPABASE_SERVICE_ROLE_KEY || '', { auth: { persistSession: false } });
const rawSupabaseUrl = process.env.SUPABASE_URL || '';
const supabaseUrl = rawSupabaseUrl.replace(/\/rest\/v1\/?$/, '');
//const supabase = createClient(supabaseUrl, process.env.SUPABASE_SERVICE_ROLE_KEY || '', { auth: { persistSession: false } });
const supabaseKey = String(
  process.env.supabase_server_key ||
  process.env.SUPABASE_SERVICE_ROLE_KEY ||
  ''
).trim();

const supabase = createClient(supabaseUrl, supabaseKey, { auth: { persistSession: false } });
const SECRET = process.env.JWT_SECRET || 'CHANGE-ME-IN-VERCEL';
const STORAGE_BUCKET = process.env.SUPABASE_STORAGE_BUCKET || 'lucky-draw';

app.use(express.json({ limit: '15mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(process.cwd(), 'public')));

function now(){ return new Date().toISOString(); }
function normalizeName(v){ return String(v || '').trim().replace(/\s+/g,' ').toUpperCase(); }
function normalizeNric(v){ return String(v || '').replace(/[^0-9A-Za-z]/g,'').toUpperCase(); }
function normalizePhone(v){ let s=String(v||'').replace(/[^0-9+]/g,''); if(s.startsWith('+60')) s='0'+s.slice(3); else if(s.startsWith('60')) s='0'+s.slice(2); return s; }
function maskNric(v){ const s=String(v||''); return 'XXXX'+s.slice(-4); }
function mapEvent(e){ return e && ({id:e.id,title:e.title,date:e.date,venue:e.venue,organizer:e.organizer,totalDraws:e.total_draws,background:e.background||'',backgroundType:e.background_type||'',logo:e.logo||'',status:e.status,createdAt:e.created_at}); }
function mapPrize(p){ return {id:p.id,eventId:p.event_id,level:p.level,name:p.name,description:p.description||'',quantity:p.quantity,drawOrder:p.draw_order,image:p.image||''}; }
function mapParticipant(p,full=false){ return {id:p.id,eventId:p.event_id,registrationNo:p.registration_no,fullName:p.full_name,nric:full?p.nric:maskNric(p.nric),contact:p.contact,registeredAt:p.registered_at,status:p.status}; }
function requireEnv(res){ if(!process.env.SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) { res.status(500).json({error:'Supabase environment variables are not configured in Vercel.'}); return false; } return true; }
function auth(req,res,next){ try { const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,''); req.user=jwt.verify(token,SECRET); next(); } catch { res.status(401).json({error:'Unauthorized'}); } }
async function one(table, query){ const {data,error}=await query; if(error) throw error; return data?.[0]||null; }
async function list(table, query){ const {data,error}=await query; if(error) throw error; return data||[]; }
async function getEvent(id){ return one('events', supabase.from('events').select('*').eq('id',id).limit(1)); }
async function uploadFile(file, folder){ if(!file) return ''; const ext=(file.originalname||'').includes('.') ? '.'+file.originalname.split('.').pop().toLowerCase() : ''; const filePath=`${folder}/${uuid()}${ext}`; const {error}=await supabase.storage.from(STORAGE_BUCKET).upload(filePath,file.buffer,{contentType:file.mimetype||'application/octet-stream',upsert:false}); if(error) throw error; const {data}=supabase.storage.from(STORAGE_BUCKET).getPublicUrl(filePath); return data.publicUrl; }
async function duplicateReason(eventId, fullName, nric, contact, excludeId=null){
  const checks=[['name_key',normalizeName(fullName),'Full Name'],['nric_key',normalizeNric(nric),'NRIC Number'],['contact_key',normalizePhone(contact),'Contact Number']];
  for(const [field,value,label] of checks){ if(!value) continue; let q=supabase.from('participants').select('*').eq('event_id',eventId).eq(field,value).limit(1); if(excludeId) q=q.neq('id',excludeId); const r=await one('participants',q); if(r) return {participant:r,reasons:[label]}; }
  return null;
}
async function nextRegistration(eventId){ const rows=await list('participants',supabase.from('participants').select('registration_no').eq('event_id',eventId).order('registration_no',{ascending:false}).limit(1)); const n=rows.length?Number(String(rows[0].registration_no).replace(/\D/g,''))+1:1; return 'LD-'+String(n).padStart(5,'0'); }
async function saveParticipant(eventId,body){
  const fullName=String(body.fullName||'').trim(), nric=String(body.nric||'').trim(), contact=String(body.contact||'').trim();
  if(!fullName||!nric||!contact) throw Object.assign(new Error('Full Name, NRIC Number and Contact Number are required.'),{status:400});
  const dup=await duplicateReason(eventId,fullName,nric,contact); if(dup) throw Object.assign(new Error('Participant is already registered.'),{status:409,duplicate:dup});
  const p={id:uuid(),event_id:eventId,registration_no:await nextRegistration(eventId),full_name:fullName,name_key:normalizeName(fullName),nric,nric_key:normalizeNric(nric),contact,contact_key:normalizePhone(contact),registered_at:now(),status:'ELIGIBLE'};
  const {data,error}=await supabase.from('participants').insert(p).select('*').single(); if(error){ if(error.code==='23505') throw Object.assign(new Error('Participant is already registered.'),{status:409}); throw error; } return data;
}
async function getEventData(id){ const e=await getEvent(id); if(!e) return null; const [prizes,participants,draws]=await Promise.all([
  list('prizes',supabase.from('prizes').select('*').eq('event_id',id).order('draw_order',{ascending:true})),
  list('participants',supabase.from('participants').select('*').eq('event_id',id).order('registered_at',{ascending:true})),
  list('draws',supabase.from('draws').select('*').eq('event_id',id).order('sequence',{ascending:true}))
 ]); return {event:mapEvent(e),prizes:prizes.map(mapPrize),participants:participants.map(p=>mapParticipant(p)),draws}; }

app.get('/api/health',(req,res)=>res.json({ok:true,online:true}));
app.post('/api/login',async(req,res)=>{ try { if(!requireEnv(res)) return; const username=String(req.body.username||'').trim(); const password=String(req.body.password||''); if(!username||!password)return res.status(400).json({error:'Username and password are required.'}); let u=await one('users',supabase.from('users').select('*').eq('username',username).limit(1));
  if(!u && username===String(process.env.ADMIN_USERNAME||'admin') && password===String(process.env.ADMIN_PASSWORD||'admin123')){ const created={id:uuid(),username,password:await bcrypt.hash(password,10),created_at:now()}; const r=await supabase.from('users').insert(created).select('*').single(); if(r.error) throw r.error; u=r.data; }
  if(!u || !(await bcrypt.compare(password,u.password))) return res.status(401).json({error:'Invalid login'}); res.json({token:jwt.sign({id:u.id,username:u.username},SECRET,{expiresIn:'12h'})});
 } catch(e){res.status(500).json({error:e.message||'Login failed'});} });
app.get('/api/network',auth,(req,res)=>res.json({online:true,registerUrl:`${req.protocol}://${req.get('host')}/register.html`}));
app.get('/api/events',auth,async(req,res)=>{try{res.json((await list('events',supabase.from('events').select('*').order('created_at',{ascending:false}))).map(mapEvent));}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/events',auth,upload.fields([{name:'background',maxCount:1},{name:'logo',maxCount:1}]),async(req,res)=>{try{const f=req.files||{},bg=f.background?.[0],logo=f.logo?.[0];const id=uuid();const bgUrl=await uploadFile(bg,`events/${id}/background`);const logoUrl=await uploadFile(logo,`events/${id}/logo`);const row={id,title:String(req.body.title||'').trim(),date:req.body.date||'',venue:req.body.venue||'',organizer:req.body.organizer||'',total_draws:Number(req.body.totalDraws||0),background:bgUrl,background_type:bg?.mimetype||'',logo:logoUrl,status:'OPEN',created_at:now()};const {data,error}=await supabase.from('events').insert(row).select('*').single();if(error)throw error;res.json(mapEvent(data));}catch(e){res.status(500).json({error:e.message});}});
app.put('/api/events/:id',auth,upload.fields([{name:'background',maxCount:1},{name:'logo',maxCount:1}]),async(req,res)=>{try{const e=await getEvent(req.params.id);if(!e)return res.status(404).json({error:'Event not found'});const f=req.files||{},bg=f.background?.[0],logo=f.logo?.[0];const patch={title:req.body.title??e.title,date:req.body.date??e.date,venue:req.body.venue??e.venue,organizer:req.body.organizer??e.organizer,total_draws:req.body.totalDraws!==undefined?Number(req.body.totalDraws):e.total_draws,status:req.body.status==='CLOSED'?'CLOSED':'OPEN'};if(bg){patch.background=await uploadFile(bg,`events/${e.id}/background`);patch.background_type=bg.mimetype;}if(logo)patch.logo=await uploadFile(logo,`events/${e.id}/logo`);const {data,error}=await supabase.from('events').update(patch).eq('id',e.id).select('*').single();if(error)throw error;res.json(mapEvent(data));}catch(e){res.status(500).json({error:e.message});}});
app.patch('/api/events/:id/status',auth,async(req,res)=>{try{const e=await getEvent(req.params.id);if(!e)return res.status(404).json({error:'Event not found'});const status=req.body.status==='OPEN'?'OPEN':'CLOSED';const {error}=await supabase.from('events').update({status}).eq('id',e.id);if(error)throw error;res.json({status});}catch(e){res.status(500).json({error:e.message});}});
app.delete('/api/events/:id',auth,async(req,res)=>{try{const e=await getEvent(req.params.id);if(!e)return res.status(404).json({error:'Event not found'});const {error}=await supabase.from('events').delete().eq('id',e.id);if(error)throw error;res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/events/:id/data',auth,async(req,res)=>{try{const d=await getEventData(req.params.id);if(!d)return res.status(404).json({error:'Event not found'});res.json(d);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/events/:id/participants',auth,async(req,res)=>{try{const e=await getEvent(req.params.id);if(!e)return res.status(404).json({error:'Event not found'});const p=await saveParticipant(e.id,req.body);res.json({participant:mapParticipant(p),message:'Participant registered successfully.'});}catch(e){res.status(e.status||500).json({error:e.message,duplicate:e.duplicate?{registrationNo:e.duplicate.participant.registration_no,reasons:e.duplicate.reasons}:undefined});}});
app.delete('/api/participants/:id',auth,async(req,res)=>{try{const p=await one('participants',supabase.from('participants').select('*').eq('id',req.params.id).limit(1));if(!p)return res.status(404).json({error:'Participant not found'});const d=await one('draws',supabase.from('draws').select('id').eq('participant_id',p.id).limit(1));if(d)return res.status(400).json({error:'Winner records cannot be deleted. Remove/reset the event instead.'});const {error}=await supabase.from('participants').delete().eq('id',p.id);if(error)throw error;res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/events/:id/import',auth,async(req,res)=>{try{const e=await getEvent(req.params.id);if(!e)return res.status(404).json({error:'Event not found'});const rows=Array.isArray(req.body.rows)?req.body.rows:[];let added=0,duplicates=0,errors=[];for(const row of rows){try{await saveParticipant(e.id,{fullName:row.fullName||row['Full Name'],nric:row.nric||row.NRIC,contact:row.contact||row.Contact});added++;}catch(x){if(x.status===409)duplicates++;else errors.push(x.message);}}res.json({added,duplicates,errors});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/events/:id/prizes',auth,upload.single('image'),async(req,res)=>{try{const e=await getEvent(req.params.id);if(!e)return res.status(404).json({error:'Event not found'});const id=uuid();const image=await uploadFile(req.file,`events/${id}/prizes`);const row={id,event_id:e.id,level:req.body.level||'',name:req.body.name||'',description:req.body.description||'',quantity:Math.max(1,Number(req.body.quantity||1)),draw_order:Math.max(1,Number(req.body.drawOrder||1)),image,created_at:now()};const {data,error}=await supabase.from('prizes').insert(row).select('*').single();if(error)throw error;res.json(mapPrize(data));}catch(e){res.status(500).json({error:e.message});}});
app.put('/api/prizes/:id',auth,upload.single('image'),async(req,res)=>{try{const p=await one('prizes',supabase.from('prizes').select('*').eq('id',req.params.id).limit(1));if(!p)return res.status(404).json({error:'Prize not found'});const patch={level:req.body.level??p.level,name:req.body.name??p.name,description:req.body.description??p.description,quantity:Number(req.body.quantity??p.quantity),draw_order:Number(req.body.drawOrder??p.draw_order)};if(req.file)patch.image=await uploadFile(req.file,`events/${p.event_id}/prizes`);const {data,error}=await supabase.from('prizes').update(patch).eq('id',p.id).select('*').single();if(error)throw error;res.json(mapPrize(data));}catch(e){res.status(500).json({error:e.message});}});
app.delete('/api/prizes/:id',auth,async(req,res)=>{try{const p=await one('prizes',supabase.from('prizes').select('*').eq('id',req.params.id).limit(1));if(!p)return res.status(404).json({error:'Prize not found'});const d=await one('draws',supabase.from('draws').select('id').eq('prize_id',p.id).limit(1));if(d)return res.status(400).json({error:'Prize already used in a draw.'});const {error}=await supabase.from('prizes').delete().eq('id',p.id);if(error)throw error;res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/public/:id',async(req,res)=>{try{const e=await getEvent(req.params.id);if(!e)return res.status(404).json({error:'Event not found'});res.json({event:mapEvent(e)});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/public/:id/register',async(req,res)=>{try{const e=await getEvent(req.params.id);if(!e)return res.status(404).json({error:'Event not found'});if(e.status!=='OPEN')return res.status(400).json({error:'Registration is currently closed for this event.'});const p=await saveParticipant(e.id,req.body);res.json({registrationNo:p.registration_no,message:'Registration successful.'});}catch(e){res.status(e.status||500).json({error:e.message,duplicate:e.duplicate?{registrationNo:e.duplicate.participant.registration_no,reasons:e.duplicate.reasons}:undefined});}});
app.get('/api/events/:id/qr',auth,async(req,res)=>{try{const e=await getEvent(req.params.id);if(!e)return res.status(404).json({error:'Event not found'});const url=`${req.protocol}://${req.get('host')}/register.html?event=${e.id}`;res.json({url,dataUrl:await QRCode.toDataURL(url,{width:900,margin:4,errorCorrectionLevel:'H'})});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/events/:id/draw',auth,async(req,res)=>{try{const e=await getEvent(req.params.id);if(!e)return res.status(404).json({error:'Event not found'});const pending=await list('draws',supabase.from('draws').select('*,prizes(level,name)').eq('event_id',e.id).is('collected_at',null).order('sequence',{ascending:false}).limit(1));if(pending.length)return res.status(400).json({error:`Collect or reroll the current winner before drawing the next prize. Current: ${pending[0].prizes?.level||''} - ${pending[0].prizes?.name||''}`});const prizes=await list('prizes',supabase.from('prizes').select('*').eq('event_id',e.id).order('draw_order',{ascending:true}));const draws=await list('draws',supabase.from('draws').select('prize_id,participant_id,sequence').eq('event_id',e.id));let prize=null;for(const p of prizes){const used=draws.filter(d=>d.prize_id===p.id).length;if(used<p.quantity){prize=p;break;}}if(!prize)return res.status(400).json({error:'All prize quantities have already been drawn.'});const usedIds=new Set(draws.map(d=>d.participant_id));const participants=await list('participants',supabase.from('participants').select('*').eq('event_id',e.id).eq('status','ELIGIBLE'));const pool=participants.filter(p=>!usedIds.has(p.id));if(!pool.length)return res.status(400).json({error:'No eligible participants remain.'});const winner=pool[Math.floor(Math.random()*pool.length)];const sequence=draws.length+1;const row={id:uuid(),event_id:e.id,prize_id:prize.id,participant_id:winner.id,sequence,drawn_at:now(),collected_at:null};const ins=await supabase.from('draws').insert(row).select('*').single();if(ins.error)throw ins.error;const up=await supabase.from('participants').update({status:'WINNER'}).eq('id',winner.id);if(up.error)throw up.error;res.json({draw:{...ins.data,level:prize.level,prizeName:prize.name,fullName:winner.full_name,registrationNo:winner.registration_no,nricLast4:winner.nric.slice(-4)}});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/events/:id/draw/:drawId/reroll',auth,async(req,res)=>{try{const d=await one('draws',supabase.from('draws').select('*,participants(*),prizes(level,name)').eq('id',req.params.drawId).eq('event_id',req.params.id).limit(1));if(!d)return res.status(404).json({error:'Draw not found'});const removeCurrent=String(req.body.removeCurrent||'').toLowerCase()==='true';const del=await supabase.from('draws').delete().eq('id',d.id);if(del.error)throw del.error;const up=await supabase.from('participants').update({status:removeCurrent?'REMOVED':'ELIGIBLE'}).eq('id',d.participant_id);if(up.error)throw up.error;res.json({ok:true,removed:removeCurrent});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/events/:id/draw/:drawId/collect',auth,async(req,res)=>{try{const d=await one('draws',supabase.from('draws').select('*,prizes(level,name)').eq('id',req.params.drawId).eq('event_id',req.params.id).limit(1));if(!d)return res.status(404).json({error:'Draw not found'});const collectedAt=now();const {error}=await supabase.from('draws').update({collected_at:collectedAt}).eq('id',d.id);if(error)throw error;res.json({ok:true,collectedAt});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/events/:id/winners',auth,async(req,res)=>{try{const rows=await list('draws',supabase.from('draws').select('*,participants(full_name,nric,registration_no),prizes(level,name,image)').eq('event_id',req.params.id).order('sequence',{ascending:true}));res.json(rows.map(x=>({...x,fullName:x.participants?.full_name,nric:x.participants?.nric,registrationNo:x.participants?.registration_no,level:x.prizes?.level,prizeName:x.prizes?.name,image:x.prizes?.image||'',nricLast4:(x.participants?.nric||'').slice(-4)})));}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/events/:id/participants/full',auth,async(req,res)=>{try{res.json((await list('participants',supabase.from('participants').select('*').eq('event_id',req.params.id).order('registered_at',{ascending:true}))).map(p=>mapParticipant(p,true)));}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/events/:id/backup',auth,async(req,res)=>{try{const d=await getEventData(req.params.id);if(!d)return res.status(404).json({error:'Event not found'});const full=await list('participants',supabase.from('participants').select('*').eq('event_id',req.params.id).order('registered_at',{ascending:true}));const out={version:'2.9-vercel',event:d.event,prizes:d.prizes,participants:full.map(p=>mapParticipant(p,true)),draws:d.draws,exportedAt:now()};res.setHeader('Content-Disposition',`attachment; filename="lucky-draw-${req.params.id}.json"`);res.json(out);}catch(e){res.status(500).json({error:e.message});}});

function xmlEscape(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;');}
function crc32(buf){let c=~0;for(let i=0;i<buf.length;i++){c^=buf[i];for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (~c)>>>0;}
function zipStore(files){const chunks=[],central=[];let offset=0;for(const [name,data] of files){const db=Buffer.from(data),nb=Buffer.from(name),crc=crc32(db);const local=Buffer.alloc(30+nb.length);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt16LE(0,6);local.writeUInt16LE(0,8);local.writeUInt16LE(0,10);local.writeUInt16LE(0,12);local.writeUInt32LE(crc,14);local.writeUInt32LE(db.length,18);local.writeUInt32LE(db.length,22);local.writeUInt16LE(nb.length,26);nb.copy(local,30);chunks.push(local,db);const cen=Buffer.alloc(46+nb.length);cen.writeUInt32LE(0x02014b50,0);cen.writeUInt16LE(20,4);cen.writeUInt16LE(20,6);cen.writeUInt16LE(0,8);cen.writeUInt16LE(0,10);cen.writeUInt16LE(0,12);cen.writeUInt16LE(0,14);cen.writeUInt32LE(crc,16);cen.writeUInt32LE(db.length,20);cen.writeUInt32LE(db.length,24);cen.writeUInt16LE(nb.length,28);nb.copy(cen,46);central.push(cen);offset+=local.length+db.length;}const cd=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(cd.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...chunks,cd,end]);}
function xlsxEscape(v){return xmlEscape(v);}
function makeXlsx(sheets){const files=[];files.push(['[Content_Types].xml',`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`]);files.push(['_rels/.rels',`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`]);files.push(['xl/_rels/workbook.xml.rels',`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}</Relationships>`]);files.push(['xl/workbook.xml',`<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((s,i)=>`<sheet name="${xlsxEscape(s.name).slice(0,31)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`]);sheets.forEach((sh,idx)=>{const rows=[sh.headers,...sh.rows];const xmlRows=rows.map((row,ri)=>`<row r="${ri+1}">${row.map((v,ci)=>{const col=ci<26?String.fromCharCode(65+ci):String.fromCharCode(64+Math.floor(ci/26))+String.fromCharCode(65+ci%26);return `<c r="${col}${ri+1}" t="inlineStr"><is><t>${xlsxEscape(v)}</t></is></c>`}).join('')}</row>`).join('');files.push([`xl/worksheets/sheet${idx+1}.xml`,`<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${xmlRows}</sheetData></worksheet>`]);});return zipStore(files);}
function sendXlsx(res,filename,sheets){const buf=makeXlsx(sheets);res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition',`attachment; filename="${filename}"`);res.end(buf);}
async function reportData(id){const e=await getEvent(id);if(!e)return null;const [participants,prizes,winners]=await Promise.all([list('participants',supabase.from('participants').select('*').eq('event_id',id).order('registered_at',{ascending:true})),list('prizes',supabase.from('prizes').select('*').eq('event_id',id).order('draw_order',{ascending:true})),list('draws',supabase.from('draws').select('*,participants(full_name,nric,contact),prizes(level,name)').eq('event_id',id).order('sequence',{ascending:true}))]);return {e,participants,prizes,winners};}
app.get('/api/events/:id/participants/excel',auth,async(req,res)=>{try{const d=await reportData(req.params.id);if(!d)return res.status(404).json({error:'Event not found'});sendXlsx(res,`participants-${d.e.id}.xlsx`,[{name:'Participants',headers:['Registration No','Full Name','NRIC','Contact Number','Registered At','Status'],rows:d.participants.map(r=>[r.registration_no,r.full_name,r.nric,r.contact,r.registered_at,r.status])}]);}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/events/:id/prizes/excel',auth,async(req,res)=>{try{const d=await reportData(req.params.id);if(!d)return res.status(404).json({error:'Event not found'});sendXlsx(res,`prizes-${d.e.id}.xlsx`,[{name:'Prizes',headers:['Prize Level','Prize Name','Description','Quantity','Draw Order','Picture','Created At'],rows:d.prizes.map(r=>[r.level,r.name,r.description,r.quantity,r.draw_order,r.image,r.created_at])}]);}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/events/:id/winners/excel',auth,async(req,res)=>{try{const d=await reportData(req.params.id);if(!d)return res.status(404).json({error:'Event not found'});sendXlsx(res,`winners-${d.e.id}.xlsx`,[{name:'Winners',headers:['Sequence','Prize Level','Prize Name','Winner','NRIC','Contact Number','Drawn At','Collected At'],rows:d.winners.map(r=>[r.sequence,r.prizes?.level,r.prizes?.name,r.participants?.full_name,r.participants?.nric,r.participants?.contact,r.drawn_at,r.collected_at||''])}]);}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/events/:id/report/excel',auth,async(req,res)=>{try{const d=await reportData(req.params.id);if(!d)return res.status(404).json({error:'Event not found'});const winners=d.winners;sendXlsx(res,`full-event-report-${d.e.id}.xlsx`,[{name:'Event Summary',headers:['Field','Value'],rows:[['Event Title',d.e.title],['Date',d.e.date||''],['Venue',d.e.venue||''],['Organizer',d.e.organizer||''],['Status',d.e.status],['Participants',d.participants.length],['Prize Units',d.prizes.reduce((n,p)=>n+p.quantity,0)],['Winners',winners.length],['Eligible Participants',d.participants.filter(p=>p.status==='ELIGIBLE').length],['Generated At',now()]]},{name:'Participants',headers:['Registration No','Full Name','NRIC','Contact Number','Registered At','Status'],rows:d.participants.map(r=>[r.registration_no,r.full_name,r.nric,r.contact,r.registered_at,r.status])},{name:'Prizes',headers:['Prize Level','Prize Name','Description','Quantity','Draw Order','Picture','Created At'],rows:d.prizes.map(r=>[r.level,r.name,r.description,r.quantity,r.draw_order,r.image,r.created_at])},{name:'Winners',headers:['Sequence','Prize Level','Prize Name','Winner','NRIC','Contact Number','Drawn At','Collected At'],rows:winners.map(r=>[r.sequence,r.prizes?.level,r.prizes?.name,r.participants?.full_name,r.participants?.nric,r.participants?.contact,r.drawn_at,r.collected_at||''])}]);}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/reports/events/excel',auth,async(req,res)=>{try{const events=await list('events',supabase.from('events').select('*').order('created_at',{ascending:false}));sendXlsx(res,'all-events-report.xlsx',[{name:'Events',headers:['Event Title','Date','Venue','Organizer','Status','Created At'],rows:events.map(e=>[e.title,e.date||'',e.venue||'',e.organizer||'',e.status,e.created_at])}]);}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/events/:id/reset',auth,async(req,res)=>{try{const d=await getEventData(req.params.id);if(!d)return res.status(404).json({error:'Event not found'});const full=await list('participants',supabase.from('participants').select('*').eq('event_id',req.params.id));const out={version:'2.9-vercel',event:d.event,prizes:d.prizes,participants:full.map(p=>mapParticipant(p,true)),draws:d.draws,exportedAt:now()};const del=await supabase.from('events').delete().eq('id',req.params.id);if(del.error)throw del.error;res.json({ok:true,backup:out});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/backup/database',auth,async(req,res)=>{try{const events=await list('events',supabase.from('events').select('*'));const all=[];for(const e of events){const d=await getEventData(e.id);all.push(d);}res.setHeader('Content-Type','application/json');res.setHeader('Content-Disposition',`attachment; filename="database-backup-${Date.now()}.json"`);res.json({version:'2.9-vercel',exportedAt:now(),events:all});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/system/status',auth,(req,res)=>res.json({online:true,database:'Supabase PostgreSQL',storage:STORAGE_BUCKET,node:process.version,vercel:true}));
app.get('/register.html',(req,res)=>res.sendFile(path.join(process.cwd(),'public','register.html')));

module.exports = app;
